# Generated by Django 5.1.15 on 2026-09-28 22:44

import apps.institutions.cnpj
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_code', models.CharField(db_index=True, help_text='Código IBGE oficial de 7 dígitos.', max_length=7, unique=True, verbose_name='Código IBGE')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Município')),
                ('state', models.CharField(db_index=True, max_length=2, verbose_name='UF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, help_text='CNPJ da instituição (normalizado, 14 dígitos numéricos ou padrão alfanumérico).', max_length=20, unique=True, validators=[apps.institutions.cnpj.cnpj_validator], verbose_name='CNPJ')),
                ('name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('legal_nature', models.CharField(blank=True, max_length=100, verbose_name='Natureza Jurídica')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefone de Contato')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='institutions.municipality', verbose_name='Município Sede')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
                'ordering': ['name'],
            },
        ),
    ]
