# Generated by Django 5.1.15 on 2026-09-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='ibge_code',
            field=models.CharField(blank=True, db_index=True, help_text='Código IBGE oficial de 7 dígitos.', max_length=7, null=True, unique=True, verbose_name='Código IBGE'),
        ),
        migrations.AddConstraint(
            model_name='municipality',
            constraint=models.UniqueConstraint(condition=models.Q(('ibge_code__isnull', True)), fields=('name', 'state'), name='unique_unresolved_municipality_name_state'),
        ),
    ]
