# Generated by Django 5.2.17 on 2026-09-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_municipality_ibge_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='postal_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
    ]
