# Generated by Django 5.1.15 on 2026-09-28 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editais', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo_sei', models.CharField(db_index=True, help_text='Número do processo administrativo no SEI.', max_length=50, verbose_name='Processo SEI')),
                ('received_at', models.DateTimeField(db_index=True, help_text='Timestamp oficial de protocolo da inscrição.', verbose_name='Data e Hora de Recebimento')),
                ('vagas_femininas', models.PositiveIntegerField(default=0, verbose_name='Vagas Femininas')),
                ('vagas_masculinas', models.PositiveIntegerField(default=0, verbose_name='Vagas Masculinas')),
                ('vagas_maes_nutrizes', models.PositiveIntegerField(default=0, verbose_name='Vagas Mães Nutrizes')),
                ('vagas_solicitadas', models.PositiveIntegerField(default=0, verbose_name='Total de Vagas Solicitadas')),
                ('capacidade_total', models.PositiveIntegerField(default=0, verbose_name='Capacidade Total Instalada')),
                ('valor_global', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Global Proposto (R$)')),
                ('patrimonio_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Patrimônio Líquido Mínimo Exigido (R$)')),
                ('workflow_status', models.CharField(choices=[('RECEIVED', 'Recebida'), ('ASSIGNED', 'Distribuída'), ('UNDER_ANALYSIS', 'Em Análise'), ('PENDING_REVIEW', 'Pendente de Revisão'), ('PENDING_DILIGENCE', 'Em Diligência'), ('ELIGIBLE_FOR_RANKING', 'Elegível para Ranking'), ('INELIGIBLE', 'Inabilitada / Inelegível'), ('RANKED', 'Classificada no Ranking'), ('CLOSED', 'Encerrada')], db_index=True, default='RECEIVED', max_length=30, verbose_name='Status do Workflow')),
                ('target_group', models.CharField(choices=[('G1', 'Grupo 1 (Mulheres e Mães Nutrizes)'), ('G2', 'Grupo 2 (Masculino PRONASCI)'), ('G3', 'Grupo 3 (Masculino Demais Municípios)'), ('SEM_GRUPO', 'Sem Grupo Definido')], db_index=True, default='SEM_GRUPO', max_length=20, verbose_name='Grupo de Enquadramento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='editais.edital', verbose_name='Edital')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='institutions.institution', verbose_name='Instituição Proponente')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='institutions.municipality', verbose_name='Município da Execução')),
            ],
            options={
                'verbose_name': 'Inscrição / Processo',
                'verbose_name_plural': 'Inscrições / Processos',
                'ordering': ['received_at', 'processo_sei'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Atribuição')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('REASSIGNED', 'Redistribuída'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='Status da Atribuição')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo da Redistribuição / Encerramento')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Analista Responsável')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Distribuído por')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='submissions.submission', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Atribuição de Processo',
                'verbose_name_plural': 'Atribuições de Processos',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
