# Generated by Django 5.1.15 on 2026-09-29 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_municipality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Atribuição'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='made_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Distribuído por'),
        ),
    ]
