# Generated by Django 5.1.15 on 2026-09-29 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0003_edital_duplicate_scope_edital_tie_breaker_policy'),
        ('institutions', '0002_alter_municipality_ibge_code_and_more'),
        ('submissions', '0003_alter_assignment_assigned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('submission',), name='unique_active_assignment_submission'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('edital', 'processo_sei'), name='unique_submission_edital_sei'),
        ),
    ]
