# Generated by Django 5.2.17 on 2026-09-29 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0005_program_edital_cloned_from_edital_description_and_more'),
        ('submissions', '0004_assignment_unique_active_assignment_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='target_group_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='editais.targetgroup'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='target_group',
            field=models.CharField(db_index=True, default='SEM_GRUPO', max_length=50, verbose_name='Grupo de Enquadramento'),
        ),
    ]
