# Generated by Django 5.2.17 on 2026-09-29 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0010_classificationpolicy_mixed_group_code_and_more'),
        ('submissions', '0005_submission_target_group_definition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=20, verbose_name='CNPJ')),
                ('reason', models.CharField(max_length=255)),
                ('source', models.CharField(help_text='Ex.: cadastro manual, CSV ou sistema fonte.', max_length=150)),
                ('reference_period', models.CharField(blank=True, help_text='Período de referência do contrato ou impedimento.', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_restrictions', to=settings.AUTH_USER_MODEL)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_restrictions', to='editais.edital')),
            ],
            options={
                'ordering': ['-created_at', 'cnpj'],
                'indexes': [models.Index(fields=['edital', 'cnpj', 'active'], name='submissions_edital__b15335_idx')],
            },
        ),
    ]
