# Generated by Django 5.1.15 on 2026-09-28 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Edital')),
                ('number', models.CharField(max_length=50, verbose_name='Número do Edital')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado'), ('IN_PROGRESS', 'Em Andamento'), ('SUSPENDED', 'Suspenso'), ('CLOSED', 'Encerrado'), ('ARCHIVED', 'Arquivado')], default='IN_PROGRESS', max_length=20, verbose_name='Status Operacional')),
                ('opens_at', models.DateTimeField(verbose_name='Início das Inscrições')),
                ('closes_at', models.DateTimeField(verbose_name='Término das Inscrições')),
                ('rules_version', models.CharField(default='1.0', help_text='Identificador versionado para preservar integridade de editais anteriores.', max_length=20, verbose_name='Versão das Regras')),
                ('duplicate_policy', models.CharField(choices=[('KEEP_EARLIEST_SUBMISSION', 'Manter a inscrição mais antiga (Histórico)'), ('KEEP_LATEST_SUBMISSION', 'Manter a inscrição mais recente (Retificadora)')], default='KEEP_EARLIEST_SUBMISSION', help_text='Define qual inscrição prevalece quando há duplicidade da mesma instituição.', max_length=40, verbose_name='Política de Duplicidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
                'ordering': ['-year', 'number'],
                'constraints': [models.UniqueConstraint(fields=('number', 'year'), name='unique_edital_number_year')],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código identificador do item (ex: 4.2-I, 4.2-V, 4.2-XVI).', max_length=50, verbose_name='Código do Requisito')),
                ('name', models.CharField(max_length=255, verbose_name='Título do Requisito')),
                ('description', models.TextField(blank=True, verbose_name='Descrição Detalhada')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('mandatory', models.BooleanField(default=True, help_text='Se não atendido, enseja a inaptidão da instituição.', verbose_name='Obrigatório')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='editais.edital', verbose_name='Edital')),
            ],
            options={
                'verbose_name': 'Requisito do Edital',
                'verbose_name_plural': 'Requisitos do Edital',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RequirementCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código do subitem (ex: 4.2-V-01, 4.2-V-a).', max_length=50, verbose_name='Código da Checagem')),
                ('name', models.CharField(max_length=255, verbose_name='Descrição da Checagem')),
                ('description', models.TextField(blank=True, verbose_name='Orientações ao Analista')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='editais.requirement', verbose_name='Requisito Pai')),
            ],
            options={
                'verbose_name': 'Subcritério / Checagem',
                'verbose_name_plural': 'Subcritérios / Checagens',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FundingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_group', models.CharField(help_text='Identificador do grupo (ex: G1, G2, G3 ou GERAL).', max_length=50, verbose_name='Grupo de Atendimento')),
                ('monthly_value_per_vacancy', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Mensal por Vaga (R$)')),
                ('duration_months', models.PositiveIntegerField(default=12, verbose_name='Duração em Meses')),
                ('minimum_equity_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual exigido sobre o valor global (ex: 10.00 para 10%).', max_digits=5, verbose_name='Percentual Mínimo de Patrimônio Líquido (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rules', to='editais.edital', verbose_name='Edital')),
            ],
            options={
                'verbose_name': 'Regra de Financiamento',
                'verbose_name_plural': 'Regras de Financiamento',
                'constraints': [models.UniqueConstraint(fields=('edital', 'target_group'), name='unique_edital_target_group_funding')],
            },
        ),
        migrations.CreateModel(
            name='ProgramMunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(db_index=True, default='PRONASCI', max_length=100, verbose_name='Programa Governamental')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_municipalities', to='editais.edital', verbose_name='Edital')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edital_programs', to='institutions.municipality', verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Município de Programa Prioritário',
                'verbose_name_plural': 'Municípios de Programas Prioritários',
                'constraints': [models.UniqueConstraint(fields=('edital', 'municipality', 'program_name'), name='unique_edital_municipality_program')],
            },
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('edital', 'code'), name='unique_edital_requirement_code'),
        ),
        migrations.AddConstraint(
            model_name='requirementcheck',
            constraint=models.UniqueConstraint(fields=('requirement', 'code'), name='unique_requirement_check_code'),
        ),
    ]
