# Generated by Django 5.1.15 on 2026-09-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmunicipality',
            name='legacy_original_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='accepted_statuses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='contributes_to_result',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='failure_statuses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
