# Generated by Django 5.1.15 on 2026-09-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0002_programmunicipality_legacy_original_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='duplicate_scope',
            field=models.CharField(choices=[('ABSOLUTE', 'Primeira inscrição absoluta'), ('ELIGIBLE', 'Primeira inscrição elegível')], default='ABSOLUTE', max_length=20),
        ),
        migrations.AddField(
            model_name='edital',
            name='tie_breaker_policy',
            field=models.CharField(choices=[('UNRESOLVED', 'Política de empate não definida'), ('SEI_LEXICOGRAPHIC', 'Processo SEI em ordem lexicográfica')], default='UNRESOLVED', max_length=30),
        ),
    ]
