# Generated by Django 5.2.17 on 2026-09-29 14:25

import apps.editais.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0004_vacancy_type_funding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='edital',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clones', to='editais.edital'),
        ),
        migrations.AddField(
            model_name='edital',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='edital',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edital',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_editais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingrule',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Início da vigência'),
        ),
        migrations.AddField(
            model_name='fundingrule',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da vigência'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='accepted_statuses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='requirement',
            name='allowed_statuses',
            field=models.JSONField(default=apps.editais.models.allowed_check_statuses),
        ),
        migrations.AddField(
            model_name='requirement',
            name='collect_document_cnpj',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='collect_notes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='collect_numeric_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='collect_pages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='collect_sei_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='collect_valid_until',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='failure_behavior',
            field=models.CharField(choices=[('NONE', 'Somente informativo'), ('MARK_INELIGIBLE', 'Marcar inabilitado'), ('SEND_TO_REVIEW', 'Encaminhar à revisão')], default='SEND_TO_REVIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='requirement',
            name='failure_statuses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='allowed_statuses',
            field=models.JSONField(default=apps.editais.models.allowed_check_statuses),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='collect_document_cnpj',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='collect_notes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='collect_numeric_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='collect_pages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='collect_sei_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='collect_valid_until',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Obrigatório'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('CONFIGURING', 'Em configuração'), ('ACTIVE', 'Ativo'), ('CLOSED', 'Encerrado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=20, verbose_name='Status Operacional'),
        ),
        migrations.CreateModel(
            name='ClassificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('VACANCY_TARGET_POLICY_V1', 'Vagas e programa municipal (v1)'), ('MANUAL_TARGET_POLICY_V1', 'Grupo informado no cadastro (v1)')], default='VACANCY_TARGET_POLICY_V1', max_length=40)),
                ('edital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification_policy', to='editais.edital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='programmunicipality',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='municipality_links', to='editais.program'),
        ),
        migrations.CreateModel(
            name='EditalConfigurationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_version', models.CharField(max_length=20)),
                ('configuration', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuration_snapshots', to='editais.edital')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('edital', 'rules_version'), name='unique_published_edital_version')],
            },
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem / prioridade')),
                ('active', models.BooleanField(default=True)),
                ('vacancy_types', models.JSONField(blank=True, default=list)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_groups', to='editais.edital')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='editais.program')),
            ],
            options={
                'ordering': ['order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('edital', 'code'), name='unique_edital_group')],
            },
        ),
    ]
