# Generated by Django 5.2.17 on 2026-09-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0006_upgrade_existing_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmunicipality',
            name='program_name',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='Programa Governamental'),
        ),
    ]
