# Generated by Django 5.2.17 on 2026-09-29 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0007_alter_programmunicipality_program_name'),
        ('institutions', '0002_alter_municipality_ibge_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmunicipality',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edital_programs', to='institutions.municipality', verbose_name='Município'),
        ),
    ]
