# Generated by Django 5.2.17 on 2026-09-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0008_alter_programmunicipality_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacygroupfundingrule',
            name='target_group',
            field=models.CharField(help_text='Código do público atendido na configuração histórica arquivada.', max_length=50, verbose_name='Grupo de Atendimento'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='code',
            field=models.CharField(help_text='Código do item (ex: CADASTRO, REGULARIDADE).', max_length=50, verbose_name='Código do Requisito'),
        ),
        migrations.AlterField(
            model_name='requirementcheck',
            name='code',
            field=models.CharField(help_text='Código do subcritério (ex: IDENTIDADE, LICENCA).', max_length=50, verbose_name='Código da Checagem'),
        ),
    ]
