# Generated by Django 5.2.17 on 2026-09-29 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0009_alter_legacygroupfundingrule_target_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationpolicy',
            name='mixed_group_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Grupo para entidades com vagas femininas e masculinas'),
        ),
        migrations.AddField(
            model_name='edital',
            name='requires_financial_rules',
            field=models.BooleanField(default=True, verbose_name='Este edital exige cálculo financeiro por vaga'),
        ),
        migrations.AddField(
            model_name='edital',
            name='validation_reference_date',
            field=models.DateField(blank=True, help_text='Data oficial usada para validade documental e idade mínima do CNPJ.', null=True, verbose_name='Data de referência das validações'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='collect_canonical_cnpj_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='collect_cnae',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='collect_opened_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='presentation_section',
            field=models.CharField(blank=True, max_length=100, verbose_name='Seção visual no espaço do analista'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requires_checks',
            field=models.BooleanField(default=False, help_text='Use quando este requisito precisa de um ou mais checks para publicação.', verbose_name='Exige subcritérios configurados'),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='collect_canonical_cnpj_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='collect_cnae',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirementcheck',
            name='collect_opened_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classificationpolicy',
            name='policy_type',
            field=models.CharField(choices=[('VACANCY_TARGET_POLICY_V1', 'Vagas e programa municipal (v1)'), ('VACANCY_TARGET_POLICY_V2_MIXED_FIRST', 'Vagas com prioridade para entidades mistas (v2)'), ('MANUAL_TARGET_POLICY_V1', 'Grupo informado no cadastro (v1)')], default='VACANCY_TARGET_POLICY_V1', max_length=40),
        ),
        migrations.CreateModel(
            name='RequirementValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('CNPJ_MATCH_CANONICAL', 'CNPJ igual ao da candidatura'), ('DATE_NOT_EXPIRED', 'Documento vigente na data de referência'), ('CNPJ_MINIMUM_AGE', 'Idade mínima de atividade do CNPJ'), ('CNAE_REQUIRED', 'CNAE exigido')], max_length=40)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Crítica'), ('WARNING', 'Aviso')], default='CRITICAL', max_length=12)),
                ('blocks_completion', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('requirement_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='editais.requirementcheck')),
            ],
            options={
                'ordering': ['requirement_check__order', 'rule_type'],
                'constraints': [models.UniqueConstraint(fields=('requirement_check', 'rule_type'), name='unique_check_validation_rule')],
            },
        ),
    ]
