# Generated by Django 5.2.17 on 2026-09-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0010_classificationpolicy_mixed_group_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='duplicate_policy',
            field=models.CharField(choices=[('WARN_ONLY', 'Alertar e manter candidaturas para análise'), ('KEEP_EARLIEST_SUBMISSION', 'Manter a inscrição mais antiga (Histórico)'), ('KEEP_LATEST_SUBMISSION', 'Manter a inscrição mais recente (Retificadora)')], default='KEEP_EARLIEST_SUBMISSION', help_text='Define qual inscrição prevalece quando há duplicidade da mesma instituição.', max_length=40, verbose_name='Política de Duplicidade'),
        ),
    ]
