# Generated by Django 5.1.15 on 2026-09-28 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editais', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho em Andamento'), ('COMPLETED', 'Concluída')], default='DRAFT', max_length=20, verbose_name='Status da Análise')),
                ('result', models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('APTA', 'Apta'), ('INAPTA', 'Inapta')], default='EM_ANALISE', max_length=20, verbose_name='Resultado Calculado')),
                ('failed_requirement_codes', models.JSONField(blank=True, default=list, help_text='Lista explícita dos requisitos obrigatórios não atendidos ou não enviados.', verbose_name='Códigos dos Requisitos com Falha')),
                ('general_notes', models.TextField(blank=True, verbose_name='Observações Gerais da Análise')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Início da Análise')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Conclusão da Análise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Analista Avaliador')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='submissions.submission', verbose_name='Inscrição Avaliada')),
            ],
            options={
                'verbose_name': 'Análise Documental',
                'verbose_name_plural': 'Análises Documentais',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATENDE', 'Atende'), ('NAO_ATENDE', 'Não Atende'), ('NAO_ENVIADO', 'Não Enviado'), ('NAO_APLICAVEL', 'Não Aplicável'), ('EM_BRANCO', 'Não Avaliado')], default='EM_BRANCO', max_length=20, verbose_name='Status da Checagem')),
                ('sei_number', models.CharField(blank=True, max_length=100, verbose_name='Número do Documento SEI')),
                ('pages', models.CharField(blank=True, max_length=100, verbose_name='Páginas / Folhas')),
                ('document_cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ Constante no Documento')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Data de Validade da Certidão / Documento')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor Numérico / Patrimônio')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações e Justificativas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='editais.requirementcheck', verbose_name='Checagem / Subcritério')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='evaluations.evaluation', verbose_name='Análise Pai')),
            ],
            options={
                'verbose_name': 'Resultado de Checagem',
                'verbose_name_plural': 'Resultados de Checagem',
                'constraints': [models.UniqueConstraint(fields=('evaluation', 'requirement_check'), name='unique_evaluation_check_result')],
            },
        ),
    ]
