# Generated by Django 5.1.15 on 2026-09-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='legacy_raw_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início da Análise'),
        ),
    ]
