# Generated by Django 5.2.17 on 2026-09-29 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0005_program_edital_cloned_from_edital_description_and_more'),
        ('evaluations', '0002_checkresult_legacy_raw_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_and_check_results', to='editais.requirement'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='configuration_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='editais.editalconfigurationsnapshot'),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='requirement_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='editais.requirementcheck', verbose_name='Checagem / Subcritério'),
        ),
        migrations.AddConstraint(
            model_name='checkresult',
            constraint=models.UniqueConstraint(condition=models.Q(('requirement_check__isnull', True)), fields=('evaluation', 'requirement'), name='unique_evaluation_direct_requirement'),
        ),
    ]
