# Generated by Django 5.2.17 on 2026-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_checkresult_check_result_has_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkresult',
            name='canonical_cnpj_confirmed',
            field=models.BooleanField(blank=True, null=True, verbose_name='CNPJ da candidatura confirmado no Anexo I'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='cnae',
            field=models.CharField(blank=True, max_length=30, verbose_name='CNAE informado'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='opened_on',
            field=models.DateField(blank=True, null=True, verbose_name='Data de abertura do CNPJ'),
        ),
    ]
