# Generated by Django 5.1.15 on 2026-09-28 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editais', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('PRELIMINAR', 'Resultado Preliminar'), ('FINAL', 'Resultado Final'), ('HOMOLOGADO', 'Resultado Homologado')], default='PRELIMINAR', max_length=30, verbose_name='Tipo de Snapshot')),
                ('rules_version', models.CharField(max_length=20, verbose_name='Versão das Regras Aplicada')),
                ('duplicate_policy', models.CharField(max_length=50, verbose_name='Política de Duplicidade Utilizada')),
                ('is_immutable', models.BooleanField(default=True, help_text='Garante que snapshots já gerados não possam ser alterados retroativamente.', verbose_name='Imutável')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição / Justificativa da Geração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranking_snapshots', to='editais.edital', verbose_name='Edital')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_rankings', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Snapshot de Ranking',
                'verbose_name_plural': 'Snapshots de Ranking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_group', models.CharField(help_text='G1, G2, G3 ou SEM_GRUPO', max_length=20, verbose_name='Grupo Concorrido')),
                ('position', models.PositiveIntegerField(help_text='Ordem numérica no ranking do grupo.', verbose_name='Posição na Fila')),
                ('received_at', models.DateTimeField(verbose_name='Timestamp de Recebimento')),
                ('total_vacancies', models.PositiveIntegerField(default=0, verbose_name='Total de Vagas Concorridas')),
                ('is_duplicate_suppressed', models.BooleanField(default=False, help_text='Verdadeiro caso a submissão tenha sido desconsiderada devido à política de duplicidade.', verbose_name='Duplicidade Suprimida?')),
                ('qualification_status', models.CharField(max_length=50, verbose_name='Status de Habilitação / Parecer')),
                ('tie_breaker_notes', models.TextField(blank=True, verbose_name='Critérios de Desempate Aplicados')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranking_entries', to='submissions.submission', verbose_name='Inscrição Classificada')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ranking.rankingsnapshot', verbose_name='Snapshot Pai')),
            ],
            options={
                'verbose_name': 'Entrada no Ranking',
                'verbose_name_plural': 'Entradas no Ranking',
                'ordering': ['target_group', 'position'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'target_group', 'position'), name='unique_snapshot_group_position')],
            },
        ),
    ]
