# Generated by Django 5.1.15 on 2026-09-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingentry',
            name='is_duplicate_suppressed',
            field=models.BooleanField(default=False, help_text='Verdadeiro caso tenha sido desconsiderada pela política de duplicidade.', verbose_name='Duplicidade Suprimida?'),
        ),
    ]
