# Generated by Django 5.1.15 on 2026-09-29 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_alter_rankingentry_is_duplicate_suppressed'),
        ('submissions', '0003_alter_assignment_assigned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(max_length=40)),
                ('reason_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='snapshot_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rankingsnapshot',
            name='policy_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name='rankingentry',
            constraint=models.UniqueConstraint(fields=('snapshot', 'submission'), name='unique_ranked_submission_snapshot'),
        ),
        migrations.AddField(
            model_name='rankingexclusion',
            name='duplicate_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_exclusions', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='rankingexclusion',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exclusions', to='ranking.rankingsnapshot'),
        ),
        migrations.AddField(
            model_name='rankingexclusion',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranking_exclusions', to='submissions.submission'),
        ),
        migrations.AddConstraint(
            model_name='rankingexclusion',
            constraint=models.UniqueConstraint(fields=('snapshot', 'submission'), name='unique_ranking_exclusion_submission'),
        ),
    ]
