# Generated by Django 5.2.17 on 2026-09-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_rankingexclusion_rankingentry_snapshot_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingentry',
            name='target_group',
            field=models.CharField(help_text='Código do grupo configurado para o edital.', max_length=50, verbose_name='Grupo Concorrido'),
        ),
    ]
