# Generated by Django 5.1.15 on 2026-09-28 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora do Evento')),
                ('entity_type', models.CharField(db_index=True, help_text='Nome da classe ou domínio afetado (ex: Submission, Evaluation, Review).', max_length=100, verbose_name='Tipo da Entidade')),
                ('entity_id', models.CharField(db_index=True, max_length=100, verbose_name='ID da Entidade')),
                ('action', models.CharField(db_index=True, help_text='Ex: CREATE, UPDATE, TRANSITION, ASSIGN, DILIGENCE_OPENED, RANKING_SNAPSHOT.', max_length=50, verbose_name='Ação Executada')),
                ('field', models.CharField(blank=True, max_length=100, verbose_name='Campo Alterado')),
                ('old_value', models.TextField(blank=True, verbose_name='Valor Anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='Novo Valor')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados Adicionais')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Evento de Auditoria',
                'verbose_name_plural': 'Eventos de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
