# Generated by Django 5.1.15 on 2026-09-29 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editais', '0002_programmunicipality_legacy_original_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='RUNNING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(default='strict', max_length=10)),
                ('edital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='editais.edital')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=10)),
                ('sheet', models.CharField(max_length=100)),
                ('row', models.PositiveIntegerField(null=True)),
                ('column', models.CharField(blank=True, max_length=10)),
                ('processo_sei', models.CharField(blank=True, max_length=50)),
                ('code', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('raw_value', models.JSONField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='legacy_import.legacyimportrun')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyEntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sha256', models.CharField(max_length=64)),
                ('sheet', models.CharField(max_length=100)),
                ('row', models.PositiveIntegerField()),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editais.edital')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('edital', 'source_sha256', 'sheet', 'row', 'entity_type'), name='unique_legacy_entity_source')],
            },
        ),
        migrations.CreateModel(
            name='LegacySourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=100)),
                ('row', models.PositiveIntegerField()),
                ('processo_sei', models.CharField(blank=True, max_length=50)),
                ('raw_values', models.JSONField(default=dict)),
                ('formulas', models.JSONField(default=dict)),
                ('entities', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='legacy_import.legacyimportrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'sheet', 'row'), name='unique_legacy_run_sheet_row')],
            },
        ),
    ]
