# Generated by Django 5.1.15 on 2026-09-28 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Solicitação')),
                ('reason', models.TextField(help_text='Detalhes dos itens ou inconsistências a serem esclarecidos.', verbose_name='Motivo e Fundamentação da Diligência')),
                ('deadline', models.DateField(verbose_name='Prazo Limite para Resposta')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('response', models.TextField(blank=True, verbose_name='Teor da Resposta Apresentada')),
                ('result', models.CharField(choices=[('PENDENTE', 'Pendente de Julgamento'), ('SANEADA', 'Falha Saneada / Acolhida'), ('NAO_SANEADA', 'Não Saneada / Mantida Inaptidão')], default='PENDENTE', max_length=20, verbose_name='Resultado da Diligência')),
                ('status', models.CharField(choices=[('OPEN', 'Aberta / Aguardando Resposta'), ('ANSWERED', 'Respondida'), ('CONCLUDED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=20, verbose_name='Status da Diligência')),
                ('concluded_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_diligences', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diligences', to='submissions.submission', verbose_name='Inscrição Objeto de Diligência')),
            ],
            options={
                'verbose_name': 'Diligência',
                'verbose_name_plural': 'Diligências',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente de Decisão'), ('COMPLETED', 'Revisão Concluída')], default='PENDING', max_length=20, verbose_name='Status da Revisão')),
                ('preliminary_result', models.CharField(choices=[('PRE_HABILITADO', 'Pré-Habilitado'), ('PRE_INABILITADO', 'Pré-Inabilitado'), ('PENDING_DECISION', 'Pendente de Conclusão')], default='PENDING_DECISION', max_length=30, verbose_name='Resultado Preliminar da Revisão')),
                ('decision_notes', models.TextField(blank=True, verbose_name='Fundamentação da Decisão do Revisor')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='evaluations.evaluation', verbose_name='Análise Original')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Revisor Responsável')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submission', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Revisão de Análise',
                'verbose_name_plural': 'Revisões de Análises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewItemDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrees_with_analyst', models.BooleanField(default=True, verbose_name='Concorda com o Parecer do Analista?')),
                ('reviewer_status', models.CharField(blank=True, help_text='Preenchido somente caso divirja do analista original.', max_length=20, verbose_name='Status Atribuído pelo Revisor (em divergência)')),
                ('justification', models.TextField(blank=True, help_text='Obrigatório em caso de discordância do parecer original.', verbose_name='Justificativa da Divergência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='evaluations.checkresult', verbose_name='Item da Análise Avaliado')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_decisions', to='reviews.review', verbose_name='Revisão Pai')),
            ],
            options={
                'verbose_name': 'Decisão de Item de Revisão',
                'verbose_name_plural': 'Decisões de Itens de Revisão',
                'constraints': [models.UniqueConstraint(fields=('review', 'check_result'), name='unique_review_check_result_decision')],
            },
        ),
    ]
