# Generated by Django 5.1.15 on 2026-09-29 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diligence',
            name='origin_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='diligence',
            name='unsatisfied_return_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='diligence',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo Limite para Resposta'),
        ),
        migrations.AlterField(
            model_name='diligence',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Solicitação'),
        ),
        migrations.AlterField(
            model_name='diligence',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_diligences', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AlterField(
            model_name='diligence',
            name='status',
            field=models.CharField(choices=[('LEGACY_UNKNOWN', 'Histórico: estado operacional desconhecido'), ('OPEN', 'Aberta / Aguardando Resposta'), ('ANSWERED', 'Respondida'), ('CONCLUDED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='OPEN', max_length=20, verbose_name='Status da Diligência'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Revisor Responsável'),
        ),
    ]
